# Sets default memory used for Gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx4G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

# Environment Properties
minecraft_version=26.1.2
minecraft_version_range=[26.1.2,)
neo_version=26.1.2.100
neo_version_range=[26.1.2,)

## Mod Properties
mod_id=custommachinery
mod_name=Custom Machinery
mod_license=GNU Lesser General Public License v3.0
mod_version=0.10.70
mod_group_id=frinn.custommachinery
mod_artifact_name=CustomMachinery-neoforge
mod_authors=Frinn
mod_description=Make your dream machines come true !
mod_url=https://www.curseforge.com/minecraft/mc-mods/custom-machinery
mod_github=https://github.com/Frinn38/Custom-Machinery
mod_issues=https://github.com/Frinn38/Custom-Machinery/issues

## Dependencies
jei_version=29.36.0.96
kubejs_version=26.1.2-8.0.6
jade_version=8651070
top_version=26.1.2_neo-14.0.0-1
mekanism_version=1.21.1-10.7.18.84
ae2_version=19.2.17
